export const getCommonName = (code) => {
    const countryNames = {
            "BES": "Caribbean Netherlands",
            "POL": "Poland",
            "CMR": "Cameroon",
            "MNE": "Montenegro",
            "NLD": "Netherlands",
            "CUB": "Cuba",
            "EST": "Estonia",
            "PNG": "Papua New Guinea",
            "GUY": "Guyana",
            "HUN": "Hungary",
            "CHN": "China",
            "PSE": "Palestine",
            "MAF": "Saint Martin",
            "KHM": "Cambodia",
            "SMR": "San Marino",
            "ISL": "Iceland",
            "SLB": "Solomon Islands",
            "SAU": "Saudi Arabia",
            "NIC": "Nicaragua",
            "CIV": "Ivory Coast",
            "BOL": "Bolivia",
            "MAR": "Morocco",
            "KNA": "Saint Kitts and Nevis",
            "MKD": "North Macedonia",
            "FRO": "Faroe Islands",
            "MOZ": "Mozambique",
            "PLW": "Palau",
            "HTI": "Haiti",
            "SGS": "South Georgia",
            "SSD": "South Sudan",
            "YEM": "Yemen",
            "ASM": "American Samoa",
            "SJM": "Svalbard and Jan Mayen",
            "SVK": "Slovakia",
            "MMR": "Myanmar",
            "BDI": "Burundi",
            "AFG": "Afghanistan",
            "FIN": "Finland",
            "AUT": "Austria",
            "CYM": "Cayman Islands",
            "GMB": "Gambia",
            "MSR": "Montserrat",
            "SRB": "Serbia",
            "MCO": "Monaco",
            "SLE": "Sierra Leone",
            "NAM": "Namibia",
            "ESP": "Spain",
            "FSM": "Micronesia",
            "PYF": "French Polynesia",
            "HND": "Honduras",
            "TUN": "Tunisia",
            "STP": "São Tomé and Príncipe",
            "AND": "Andorra",
            "GNQ": "Equatorial Guinea",
            "IRQ": "Iraq",
            "TZA": "Tanzania",
            "TUV": "Tuvalu",
            "MTQ": "Martinique",
            "SDN": "Sudan",
            "LSO": "Lesotho",
            "SWZ": "Eswatini",
            "THA": "Thailand",
            "PAK": "Pakistan",
            "WLF": "Wallis and Futuna",
            "ZAF": "South Africa",
            "IND": "India",
            "LCA": "Saint Lucia",
            "COL": "Colombia",
            "COD": "DR Congo",
            "SEN": "Senegal",
            "BIH": "Bosnia and Herzegovina",
            "GIN": "Guinea",
            "LTU": "Lithuania",
            "REU": "Réunion",
            "HMD": "Heard Island and McDonald Islands",
            "GEO": "Georgia",
            "PRI": "Puerto Rico",
            "NOR": "Norway",
            "COM": "Comoros",
            "TJK": "Tajikistan",
            "MYS": "Malaysia",
            "ARE": "United Arab Emirates",
            "KEN": "Kenya",
            "BGD": "Bangladesh",
            "FLK": "Falkland Islands",
            "VCT": "Saint Vincent and the Grenadines",
            "NFK": "Norfolk Island",
            "JOR": "Jordan",
            "DNK": "Denmark",
            "BLM": "Saint Barthélemy",
            "USA": "United States",
            "CPV": "Cape Verde",
            "ATG": "Antigua and Barbuda",
            "ATA": "Antarctica",
            "ARM": "Armenia",
            "PAN": "Panama",
            "ITA": "Italy",
            "CHE": "Switzerland",
            "MAC": "Macau",
            "BRA": "Brazil",
            "CXR": "Christmas Island",
            "DOM": "Dominican Republic",
            "GRC": "Greece",
            "BLR": "Belarus",
            "MLI": "Mali",
            "VUT": "Vanuatu",
            "KGZ": "Kyrgyzstan",
            "PRY": "Paraguay",
            "SPM": "Saint Pierre and Miquelon",
            "CAN": "Canada",
            "MDG": "Madagascar",
            "TWN": "Taiwan",
            "SXM": "Sint Maarten",
            "ZWE": "Zimbabwe",
            "TCA": "Turks and Caicos Islands",
            "ALA": "Åland Islands",
            "FRA": "France",
            "SYC": "Seychelles",
            "GTM": "Guatemala",
            "UZB": "Uzbekistan",
            "FJI": "Fiji",
            "VGB": "British Virgin Islands",
            "UKR": "Ukraine",
            "CYP": "Cyprus",
            "VNM": "Vietnam",
            "CCK": "Cocos (Keeling) Islands",
            "IOT": "British Indian Ocean Territory",
            "ZMB": "Zambia",
            "QAT": "Qatar",
            "SYR": "Syria",
            "TGO": "Togo",
            "ALB": "Albania",
            "SHN": "Saint Helena, Ascension and Tristan da Cunha",
            "MNP": "Northern Mariana Islands",
            "LUX": "Luxembourg",
            "NIU": "Niue",
            "JPN": "Japan",
            "LAO": "Laos",
            "ERI": "Eritrea",
            "NZL": "New Zealand",
            "SOM": "Somalia",
            "MEX": "Mexico",
            "GRD": "Grenada",
            "BVT": "Bouvet Island",
            "LKA": "Sri Lanka",
            "BWA": "Botswana",
            "UNK": "Kosovo",
            "MDV": "Maldives",
            "IRN": "Iran",
            "BLZ": "Belize",
            "HKG": "Hong Kong",
            "MLT": "Malta",
            "SWE": "Sweden",
            "GIB": "Gibraltar",
            "PER": "Peru",
            "DZA": "Algeria",
            "BRB": "Barbados",
            "KWT": "Kuwait",
            "TKL": "Tokelau",
            "PRK": "North Korea",
            "TKM": "Turkmenistan",
            "GUF": "French Guiana",
            "BTN": "Bhutan",
            "DEU": "Germany",
            "RUS": "Russia",
            "CHL": "Chile",
            "MYT": "Mayotte",
            "VIR": "United States Virgin Islands",
            "ETH": "Ethiopia",
            "COG": "Republic of the Congo",
            "JAM": "Jamaica",
            "ABW": "Aruba",
            "ISR": "Israel",
            "KOR": "South Korea",
            "IMN": "Isle of Man",
            "TLS": "Timor-Leste",
            "BHR": "Bahrain",
            "GLP": "Guadeloupe",
            "SGP": "Singapore",
            "BMU": "Bermuda",
            "GGY": "Guernsey",
            "COK": "Cook Islands",
            "MRT": "Mauritania",
            "BEN": "Benin",
            "IDN": "Indonesia",
            "BEL": "Belgium",
            "TON": "Tonga",
            "URY": "Uruguay",
            "SVN": "Slovenia",
            "VAT": "Vatican City",
            "BFA": "Burkina Faso",
            "AZE": "Azerbaijan",
            "PHL": "Philippines",
            "MUS": "Mauritius",
            "AGO": "Angola",
            "NGA": "Nigeria",
            "GNB": "Guinea-Bissau",
            "GBR": "United Kingdom",
            "CUW": "Curaçao",
            "PCN": "Pitcairn Islands",
            "NCL": "New Caledonia",
            "SLV": "El Salvador",
            "ARG": "Argentina",
            "WSM": "Samoa",
            "ATF": "French Southern and Antarctic Lands",
            "LBN": "Lebanon",
            "NPL": "Nepal",
            "EGY": "Egypt",
            "ECU": "Ecuador",
            "GAB": "Gabon",
            "KAZ": "Kazakhstan",
            "BHS": "Bahamas",
            "HRV": "Croatia",
            "ROU": "Romania",
            "GHA": "Ghana",
            "TTO": "Trinidad and Tobago",
            "UGA": "Uganda",
            "MDA": "Moldova",
            "IRL": "Ireland",
            "LBR": "Liberia",
            "CZE": "Czechia",
            "MHL": "Marshall Islands",
            "JEY": "Jersey",
            "UMI": "United States Minor Outlying Islands",
            "GUM": "Guam",
            "GRL": "Greenland",
            "CAF": "Central African Republic",
            "AUS": "Australia",
            "TCD": "Chad",
            "OMN": "Oman",
            "TUR": "Turkey",
            "ESH": "Western Sahara",
            "MWI": "Malawi",
            "AIA": "Anguilla",
            "NRU": "Nauru",
            "LVA": "Latvia",
            "DMA": "Dominica",
            "SUR": "Suriname",
            "RWA": "Rwanda",
            "NER": "Niger",
            "BRN": "Brunei",
            "PRT": "Portugal",
            "VEN": "Venezuela",
            "BGR": "Bulgaria",
            "DJI": "Djibouti",
            "LIE": "Liechtenstein",
            "KIR": "Kiribati",
            "MNG": "Mongolia",
            "CRI": "Costa Rica",
            "LBY": "Libya"
        
    }
    return countryNames[code]
}
